apiVersion: v1
kind: Namespace
metadata:
  name: ns1
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-ingress
  namespace: ns1
spec:
  rules:
  - host: abc.com
