apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-dev-ingress
  namespace: dev
spec:
  rules:
  - host: abc.com
